### ISSUE TITLE
using `/` instead of `?`

### ISSUE THREAD

**Issue by azinsharaf** [aditya-K2/gspt#9]
I just downloaded it today. Great job!

Since the Vim key-bindingsis being used (jk) that would be nice if we use `/` instead of `?` to search the tracks. And use `?` to show the help/default key-bindings.

**Comment by aditya-K2** [comment]
I had this in mind for quite a while now. I mapped it this way because I wanted to implement buffer searching where `/` would be used to search the current buffer and `?` to search Spotify. 

But your suggestion seems to make more sense. Still, I will wait until I implement buffer searching to see what kind of mappings would be used for buffer searching (maybe `ctrl-f` or `ctrl-/`) 

With the recent commits you can map `/` to `focus_search`. 
```yaml
mappings:
  global:
    focus_search: "/"
```

**Comment by azinsharaf** [comment]
Sounds like a plan.
